// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_posts_slug_ from "./routes/api/posts/[slug].ts";
import * as $api_posts_index from "./routes/api/posts/index.ts";
import * as $index from "./routes/index.tsx";
import * as $previous_slug_ from "./routes/previous/[slug].ts";
import * as $previous_index from "./routes/previous/index.tsx";
import * as $Index from "./islands/Index.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/posts/[slug].ts": $api_posts_slug_,
    "./routes/api/posts/index.ts": $api_posts_index,
    "./routes/index.tsx": $index,
    "./routes/previous/[slug].ts": $previous_slug_,
    "./routes/previous/index.tsx": $previous_index,
  },
  islands: {
    "./islands/Index.tsx": $Index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
